In [239]:
import pandas as pd
import numpy as np

Loading File

In [240]:
df = pd.read_csv('cereals.csv')

In [241]:
cols = list(df.columns)

In [242]:
missing = df['carbo']== -1

In [243]:
# Replace all -1 with NaNs
for col in cols:
    missing = df[col] == -1
    df[col][missing] = np.nan

/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [287]:
# replace all the values with mean
df = df.fillna(df.mean())

In [288]:
corr_matrix = df.corr()

In [289]:
high_corr = corr_matrix > 0.5

In [290]:
corr_matrix[high_corr]

calories   protein  fat  sodium     fiber  carbo    sugars  \
calories  1.000000       NaN  NaN     NaN       NaN    NaN  0.566062   
protein        NaN  1.000000  NaN     NaN  0.500330    NaN       NaN   
fat            NaN       NaN    1     NaN       NaN    NaN       NaN   
sodium         NaN       NaN  NaN       1       NaN    NaN       NaN   
fiber          NaN  0.500330  NaN     NaN  1.000000    NaN       NaN   
carbo          NaN       NaN  NaN     NaN       NaN      1       NaN   
sugars    0.566062       NaN  NaN     NaN       NaN    NaN  1.000000   
potass         NaN  0.562143  NaN     NaN  0.908647    NaN       NaN   
vitamins       NaN       NaN  NaN     NaN       NaN    NaN       NaN   
shelf          NaN       NaN  NaN     NaN       NaN    NaN       NaN   
weight    0.696091       NaN  NaN     NaN       NaN    NaN       NaN   
cups           NaN       NaN  NaN     NaN       NaN    NaN       NaN   
c5             NaN       NaN  NaN     NaN       NaN    NaN       NaN   

            potass  vitamins  shelf    weight  cups  c5  
calories       NaN       NaN    NaN  0.696091   NaN NaN  
protein   0.562143       NaN    NaN       NaN   NaN NaN  
fat            NaN       NaN    NaN       NaN   NaN NaN  
sodium         NaN       NaN    NaN       NaN   NaN NaN  
fiber     0.908647       NaN    NaN       NaN   NaN NaN  
carbo          NaN       NaN    NaN       NaN   NaN NaN  
sugars         NaN       NaN    NaN       NaN   NaN NaN  
potass    1.000000       NaN    NaN       NaN   NaN NaN  
vitamins       NaN         1    NaN       NaN   NaN NaN  
shelf          NaN       NaN      1       NaN   NaN NaN  
weight         NaN       NaN    NaN  1.000000   NaN NaN  
cups           NaN       NaN    NaN       NaN     1 NaN  
c5             NaN       NaN    NaN       NaN   NaN   1

High Correlation between Protein and Potassium, weight and calories, sugars and calories, potassium and fiber (Minimum correlation greater than 0.5). However the highest of these (> 80) is between Potassium and Fiber at 0.9

In [291]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'c5'],
      dtype='object')

In [292]:
#features reduction for clustering. Will look at those with correlation greater than 0.5
cols = ['sugars', 'calories', 'protein', 'fiber', 'potass']
X = df[cols]
Y = df[['name']]
cereal_data = df[df.columns]

In [293]:
X.head()

sugars  calories  protein  fiber      potass
0       6        70        4     10  280.000000
1       8       120        3      2  135.000000
2       5        70        4      9  320.000000
3       0        50        4     14  330.000000
4       8       110        2      1   98.666667

In [294]:
X.head()

sugars  calories  protein  fiber      potass
0       6        70        4     10  280.000000
1       8       120        3      2  135.000000
2       5        70        4      9  320.000000
3       0        50        4     14  330.000000
4       8       110        2      1   98.666667

In [295]:
from sklearn.cluster import KMeans
from sklearn import preprocessing
import matplotlib.pyplot as plt
import matplotlib

In [296]:
#Scaling the data
scaled_data = preprocessing.scale(X)

In [297]:
# clusters
def clusters(no_clusters, data=scaled_data):
    kmeans = KMeans(no_clusters)
    kmeans.fit(data)
    return kmeans.predict(data) # Labels the original data set based on the similarity/closeness between values

In [298]:
clusters(3)

array([2, 0, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1], dtype=int32)

In [299]:
clusters(4)

array([3, 0, 3, 3, 2, 2, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 0, 1, 1, 2,
       1, 2, 2, 1, 0, 0, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 1, 2, 1, 0, 0,
       0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 0, 1, 1, 2, 1, 1, 2], dtype=int32)

In [300]:
c5 = clusters(5)

In [301]:
clusters(6)

array([3, 2, 3, 3, 1, 1, 1, 5, 2, 2, 1, 0, 1, 2, 1, 4, 4, 1, 1, 2, 4, 4, 2,
       4, 1, 1, 2, 5, 5, 1, 1, 1, 2, 2, 2, 1, 2, 1, 4, 5, 4, 0, 1, 0, 5, 5,
       5, 2, 1, 5, 2, 5, 5, 4, 4, 4, 0, 0, 5, 2, 2, 4, 4, 4, 2, 2, 1, 0, 2,
       4, 5, 2, 4, 1, 2, 2, 1], dtype=int32)

In [302]:
clusters(16)

array([10,  9, 10,  3,  4,  4, 13,  9, 14, 11,  0,  8,  0,  7,  0,  5,  5,
        0,  0,  7,  1,  5,  4, 14, 13,  0,  7,  2,  2,  0, 13,  0, 11, 11,
       11,  0,  4,  0,  4,  9,  5, 15, 13, 15, 12, 12, 12, 14,  4,  9,  1,
        9,  2,  5,  6,  6, 15, 15,  2,  7, 14,  5,  5,  1,  1,  1, 13,  8,
       14,  5,  2, 11,  5,  0, 11, 11,  4], dtype=int32)

In [303]:
df["c5"] = c5

In [304]:
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100%_Bran   N    C        70        4    1     130     10   
1          100%_Natural_Bran   Q    C       120        3    5      15      2   
2                   All-Bran   K    C        70        4    1     260      9   
3  All-Bran_with_Extra_Fiber   K    C        50        4    0     140     14   
4             Almond_Delight   R    C       110        2    2     200      1   

   carbo  sugars      potass  vitamins  shelf  weight  cups  c5  
0      5       6  280.000000        25      3       1  0.33   3  
1      8       8  135.000000         0      3       1  1.00   1  
2      7       5  320.000000        25      3       1  0.33   3  
3      8       0  330.000000        25      3       1  0.50   3  
4     14       8   98.666667        25      3       1  0.75   2

In [305]:
df.groupby('c5').count()

name  mfr  type  calories  protein  fat  sodium  fiber  carbo  sugars  \
c5                                                                          
0     22   22    22        22       22   22      22     22     22      22   
1     13   13    13        13       13   13      13     13     13      13   
2     22   22    22        22       22   22      22     22     22      22   
3      3    3     3         3        3    3       3      3      3       3   
4     17   17    17        17       17   17      17     17     17      17   

    potass  vitamins  shelf  weight  cups  
c5                                         
0       22        22     22      22    22  
1       13        13     13      13    13  
2       22        22     22      22    22  
3        3         3      3       3     3  
4       17        17     17      17    17

In [306]:
df[df['c5'] == 1]

name mfr type  calories  protein  fat  \
1                        100%_Natural_Bran   Q    C       120        3    5   
7                                  Basic_4   G    C       130        3    2   
27  Fruit_&_Fibre_Dates,_Walnuts,_and_Oats   P    C       120        3    2   
28                           Fruitful_Bran   K    C       120        3    0   
39                  Just_Right_Fruit_&_Nut   K    C       140        3    1   
44        Muesli_Raisins,_Dates,_&_Almonds   R    C       150        4    3   
45       Muesli_Raisins,_Peaches,_&_Pecans   R    C       150        4    3   
46                    Mueslix_Crispy_Blend   K    C       160        3    2   
49               Nutri-Grain_Almond-Raisin   K    C       140        3    2   
51                    Oatmeal_Raisin_Crisp   G    C       130        3    2   
52                   Post_Nat._Raisin_Bran   P    C       120        3    1   
58                             Raisin_Bran   K    C       120        3    1   
70                       Total_Raisin_Bran   G    C       140        3    1   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  c5  
1       15    2.0    8.0       8     135         0      3    1.00  1.00   1  
7      210    2.0   18.0       8     100        25      3    1.33  0.75   1  
27     160    5.0   12.0      10     200        25      3    1.25  0.67   1  
28     240    5.0   14.0      12     190        25      3    1.33  0.67   1  
39     170    2.0   20.0       9      95       100      3    1.30  0.75   1  
44      95    3.0   16.0      11     170        25      3    1.00  1.00   1  
45     150    3.0   16.0      11     170        25      3    1.00  1.00   1  
46     150    3.0   17.0      13     160        25      3    1.50  0.67   1  
49     220    3.0   21.0       7     130        25      3    1.33  0.67   1  
51     170    1.5   13.5      10     120        25      3    1.25  0.50   1  
52     200    6.0   11.0      14     260        25      3    1.33  0.67   1  
58     210    5.0   14.0      12     240        25      2    1.33  0.75   1  
70     190    4.0   15.0      14     230       100      3    1.50  1.00   1

In [308]:
df[df['c5'] == 2]

name mfr type  calories  protein  fat  sodium  fiber  \
4            Almond_Delight   R    C       110        2    2     200    1.0   
5   Apple_Cinnamon_Cheerios   G    C       110        2    2     180    1.5   
6               Apple_Jacks   K    C       110        2    0     125    1.0   
10             Cap'n'Crunch   Q    C       120        1    2     220    0.0   
12    Cinnamon_Toast_Crunch   G    C       120        1    3     210    0.0   
14              Cocoa_Puffs   G    C       110        1    1     180    0.0   
17                Corn_Pops   K    C       110        1    0      90    1.0   
18            Count_Chocula   G    C       110        1    1     180    0.0   
22   Crispy_Wheat_&_Raisins   G    C       100        2    1     140    2.0   
24              Froot_Loops   K    C       110        2    1     125    1.0   
25           Frosted_Flakes   K    C       110        1    0     200    1.0   
29           Fruity_Pebbles   P    C       110        1    1     135    0.0   
30             Golden_Crisp   P    C       100        2    0      45    0.0   
31           Golden_Grahams   G    C       110        1    1     280    0.0   
35         Honey_Graham_Ohs   Q    C       120        1    2     220    1.0   
36       Honey_Nut_Cheerios   G    C       110        3    1     250    1.5   
37               Honey-comb   P    C       110        1    0     180    0.0   
42             Lucky_Charms   G    C       110        2    1     180    0.0   
48         Nut&Honey_Crunch   K    C       120        2    1     190    0.0   
66                   Smacks   K    C       110        2    1      70    1.0   
73                     Trix   G    C       110        1    1     140    0.0   
76      Wheaties_Honey_Gold   G    C       110        2    1     200    1.0   

    carbo  sugars      potass  vitamins  shelf  weight  cups  c5  
4    14.0       8   98.666667        25      3       1  0.75   2  
5    10.5      10   70.000000        25      1       1  0.75   2  
6    11.0      14   30.000000        25      2       1  1.00   2  
10   12.0      12   35.000000        25      2       1  0.75   2  
12   13.0       9   45.000000        25      2       1  0.75   2  
14   12.0      13   55.000000        25      2       1  1.00   2  
17   13.0      12   20.000000        25      2       1  1.00   2  
18   12.0      13   65.000000        25      2       1  1.00   2  
22   11.0      10  120.000000        25      3       1  0.75   2  
24   11.0      13   30.000000        25      2       1  1.00   2  
25   14.0      11   25.000000        25      1       1  0.75   2  
29   13.0      12   25.000000        25      2       1  0.75   2  
30   11.0      15   40.000000        25      1       1  0.88   2  
31   15.0       9   45.000000        25      2       1  0.75   2  
35   12.0      11   45.000000        25      2       1  1.00   2  
36   11.5      10   90.000000        25      1       1  0.75   2  
37   14.0      11   35.000000        25      1       1  1.33   2  
42   12.0      12   55.000000        25      2       1  1.00   2  
48   15.0       9   40.000000        25      2       1  0.67   2  
66    9.0      15   40.000000        25      2       1  0.75   2  
73   13.0      12   25.000000        25      2       1  1.00   2  
76   16.0       8   60.000000        25      1       1  0.75   2

In [ ]:
df[df['c5'] == 2]