In [1]:
import pandas as pd
from sklearn.preprocessing import Normalizer
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

In [2]:
data = pd.read_csv('cereals.csv', na_values = -1)

In [3]:
data.head(3)

name mfr type  calories  protein  fat  sodium  fiber  carbo  \
0          100%_Bran   N    C        70        4    1     130     10      5   
1  100%_Natural_Bran   Q    C       120        3    5      15      2      8   
2           All-Bran   K    C        70        4    1     260      9      7   

   sugars  potass  vitamins  shelf  weight  cups  
0       6     280        25      3       1  0.33  
1       8     135         0      3       1  1.00  
2       5     320        25      3       1  0.33

In [4]:
counter = 0
cval = 0
for col in data.columns:
    for val in data[col]:
        cval += 1
        if val == -1:
            counter += 1
#             print('{}, {}'.format(col,cval))
    print('{} -> {}'.format(col, counter))
    counter = 0 
    cval = 0

name -> 0
mfr -> 0
type -> 0
calories -> 0
protein -> 0
fat -> 0
sodium -> 0
fiber -> 0
carbo -> 0
sugars -> 0
potass -> 0
vitamins -> 0
shelf -> 0
weight -> 0
cups -> 0


In [5]:
del data['mfr']

In [6]:
del data['type']

In [7]:
norm = Normalizer()

In [8]:
data.head()

name  calories  protein  fat  sodium  fiber  carbo  \
0                  100%_Bran        70        4    1     130     10      5   
1          100%_Natural_Bran       120        3    5      15      2      8   
2                   All-Bran        70        4    1     260      9      7   
3  All-Bran_with_Extra_Fiber        50        4    0     140     14      8   
4             Almond_Delight       110        2    2     200      1     14   

   sugars  potass  vitamins  shelf  weight  cups  
0       6     280        25      3       1  0.33  
1       8     135         0      3       1  1.00  
2       5     320        25      3       1  0.33  
3       0     330        25      3       1  0.50  
4       8     NaN        25      3       1  0.75

In [9]:
names = data['name']

In [10]:
del data['name']

In [11]:
data.truediv(data.cups, axis='index').head()

calories    protein       fat      sodium      fiber      carbo  \
0  212.121212  12.121212  3.030303  393.939394  30.303030  15.151515   
1  120.000000   3.000000  5.000000   15.000000   2.000000   8.000000   
2  212.121212  12.121212  3.030303  787.878788  27.272727  21.212121   
3  100.000000   8.000000  0.000000  280.000000  28.000000  16.000000   
4  146.666667   2.666667  2.666667  266.666667   1.333333  18.666667   

      sugars      potass   vitamins     shelf    weight  cups  
0  18.181818  848.484848  75.757576  9.090909  3.030303     1  
1   8.000000  135.000000   0.000000  3.000000  1.000000     1  
2  15.151515  969.696970  75.757576  9.090909  3.030303     1  
3   0.000000  660.000000  50.000000  6.000000  2.000000     1  
4  10.666667         NaN  33.333333  4.000000  1.333333     1

In [62]:
preprocessing.Imputer().fit_transform(data)

array([[  7.00000000e+01,   4.00000000e+00,   1.00000000e+00,
          1.30000000e+02,   1.00000000e+01,   5.00000000e+00,
          6.00000000e+00,   2.80000000e+02,   2.50000000e+01,
          3.00000000e+00,   1.00000000e+00,   3.30000000e-01],
       [  1.20000000e+02,   3.00000000e+00,   5.00000000e+00,
          1.50000000e+01,   2.00000000e+00,   8.00000000e+00,
          8.00000000e+00,   1.35000000e+02,   0.00000000e+00,
          3.00000000e+00,   1.00000000e+00,   1.00000000e+00],
       [  7.00000000e+01,   4.00000000e+00,   1.00000000e+00,
          2.60000000e+02,   9.00000000e+00,   7.00000000e+00,
          5.00000000e+00,   3.20000000e+02,   2.50000000e+01,
          3.00000000e+00,   1.00000000e+00,   3.30000000e-01],
       [  5.00000000e+01,   4.00000000e+00,   0.00000000e+00,
          1.40000000e+02,   1.40000000e+01,   8.00000000e+00,
          0.00000000e+00,   3.30000000e+02,   2.50000000e+01,
          3.00000000e+00,   1.00000000e+00,   5.00000000e-01],
    

In [48]:
class Scaled:

    def __init__(self):
        pass
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
#         return X.truediv(X.cups, axis='index')
        cups = X[:,-1]
        cups = cups.reshape(77,1)
        return X / cups

In [54]:
estimator = Pipeline([("imputer", preprocessing.Imputer()),
                      ("scaled", Scaled()),
                      ("normalize", Normalizer()),
                      ('kmeans', KMeans(4))])

In [55]:
estimator.fit_transform(data)

array([[ 0.63738215,  0.6126563 ,  0.30540663,  0.85878544],
       [ 0.13334707,  0.74466884,  0.52496142,  0.96908118],
       [ 0.79823699,  0.4798741 ,  0.2808487 ,  0.69444846],
       [ 0.69335432,  0.68441358,  0.38952426,  0.920282  ],
       [ 0.87278436,  0.10649628,  0.39781952,  0.21966921],
       [ 0.89761042,  0.14948794,  0.46998716,  0.14001178],
       [ 0.88800348,  0.30355341,  0.59795445,  0.21116786],
       [ 0.85382902,  0.09763631,  0.40889709,  0.20314213],
       [ 0.86084436,  0.16451052,  0.32784634,  0.33521035],
       [ 0.78715627,  0.2825417 ,  0.21348893,  0.50438871],
       [ 1.03705248,  0.33029082,  0.64607935,  0.06633689],
       [ 1.00463322,  0.25740433,  0.51644597,  0.20666474],
       [ 0.99762356,  0.28311573,  0.60130732,  0.04145994],
       [ 0.70119234,  0.09995895,  0.25714845,  0.36679544],
       [ 0.93673834,  0.20994863,  0.53142349,  0.0844443 ],
       [ 1.13771418,  0.425303  ,  0.72428314,  0.17687599],
       [ 1.14336127,  0.

In [56]:
estimator.predict(data)

array([2, 0, 2, 2, 1, 3, 3, 1, 1, 2, 3, 3, 3, 1, 3, 3, 3, 3, 3, 2, 2, 3, 1,
       1, 3, 3, 0, 2, 1, 3, 1, 3, 1, 1, 2, 3, 3, 3, 3, 1, 3, 1, 3, 0, 2, 2,
       2, 1, 3, 1, 1, 1, 2, 3, 0, 0, 1, 0, 2, 2, 0, 3, 3, 0, 0, 0, 1, 3, 0,
       3, 2, 1, 3, 3, 1, 1, 3], dtype=int32)